export const COMPANY_NAME = "Graphico";
export const COMPANY_FACTORY_ADDRESS_LINE1 = "Gala No. 4, Electronic Ind. Estate,";
export const COMPANY_FACTORY_ADDRESS_LINE2 = "Sr. No. 126, Aml, Silvassa - 396230,";
export const COMPANY_FACTORY_ADDRESS_LINE3 = "U.T of Dadra and Nagar Haveli, India";
export const COMPANY_BRANCH_OFFICE_ADDRESS_LINE1 = "4891-92, 2nd Floor, Paras Nath Marg,";
export const COMPANY_BRANCH_OFFICE_ADDRESS_LINE2 = "Above Punjab National Bank,";
export const COMPANY_BRANCH_OFFICE_ADDRESS_LINE3 = "Opp. Westend Cinema,";
export const COMPANY_BRANCH_OFFICE_ADDRESS_LINE4= "Sadar Bazar, Delhi - 110006, India";
export const COMPANY_WEBSITE = "https://www.heattransferfoils.com";
export const COMPANY_LOGO = "https://www.heattransferfoils.com/wp-content/uploads/2023/10/graphico-logo.png";
export const COMPANY_TAGLINE = "Premium heat transfer foils solutions for your business needs.";
export const PHONE_NUMBER = "+916200861130";
export const PHONE_NUMBER_RANJEET = "+919723194999";
export const PHONE_NUMBER_AMIT = "+918840942891";
export const PHONE_NUMBER_PRADEEP = "+919833993682";
export const COMPANY_EMAIL_ADDRESS = "sales.graphico.in@gmail.com"
export const COMPANY_MOTO = "You Imagine, We Create...";
export const WHATSAPP_MESSAGE = "Hi! I would like to know more about your heat transfer foil products.";